# Generated by Django 5.0.2 on 2024-03-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_description_and_more'),
    ]

    operations = [
    ]
