# Generated by Django 5.0.2 on 2024-03-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_name_customuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Name',
            new_name='name',
        ),
    ]
