# Generated by Django 5.0.2 on 2024-03-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_name_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Name',
            new_name='name',
        ),
    ]
