# Generated by Django 5.0.4 on 2024-04-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_customuser_name_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_inactive',
            field=models.BooleanField(default=True),
        ),
    ]
