# Generated by Django 5.0.4 on 2024-05-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customuser_is_inactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_inactive',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
